[DP-2]
path = "/media/patate/Wallpapers/ultrawide"
duration = "1d"

[DP-1]
path = "/media/patate/Wallpapers/standard"
duration = "1d"

[HDMI-A-1]
path = "/media/patate/Wallpapers/standard"
duration = "1d"
